import React from 'react'
const { Component } = React

export default class LoremIpsum extends Component {
  render() {
    const { sections = 1 } = this.props
    const mapper = new Array(sections).fill(0)
    return (
      <div>
        <div>
          <h1>Lorem Ipsum</h1>
          <p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>
          <p>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."</p>
        </div>

        <hr />

        {mapper.map((x, i) => (
          <div key={i} className="section">
            <h4>Section {i}</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ullamcorper est nec diam consectetur, eu consectetur augue auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue leo quis sem molestie consectetur. Sed finibus accumsan luctus. Sed dui dui, malesuada in tortor non, lobortis dapibus elit. Nullam imperdiet rutrum dolor, a scelerisque eros pulvinar tempor. Suspendisse potenti. Nam luctus, risus sed consequat vehicula, risus justo vulputate nulla, vitae consequat justo lorem a lacus. Suspendisse quam lorem, fringilla sit amet commodo euismod, auctor sed magna. Curabitur sodales luctus lectus, id pretium tellus semper blandit. Duis ut tortor sit amet leo vestibulum lacinia. Curabitur at viverra neque. Duis vel mauris id justo mattis tempus.</p>
            <p>Praesent sit amet dolor ultricies, tincidunt dui nec, commodo nulla. Pellentesque sed nisi eget purus volutpat lobortis. Vivamus bibendum posuere lectus quis vestibulum. Nunc dictum turpis eu nunc lobortis, et vehicula lacus feugiat. Maecenas eget risus lorem. Praesent est ipsum, lobortis ut justo lacinia, elementum placerat dolor. Curabitur cursus lectus vitae nulla consectetur ornare. Phasellus iaculis tellus a accumsan condimentum. Duis id felis sed nulla fermentum pretium aliquam ut nisi. Aenean tellus neque, iaculis pharetra bibendum sit amet, ultrices sed purus. Duis quis nisl in turpis sagittis elementum quis ac orci. Morbi molestie leo sit amet imperdiet blandit. Praesent a hendrerit ipsum. Morbi consectetur mollis dolor. Duis vitae tincidunt purus. Pellentesque eget tortor lacinia, consectetur mi sit amet, consectetur dolor.</p>
            <p>Maecenas luctus feugiat ligula, in sollicitudin dui hendrerit id. Nunc luctus luctus erat, id venenatis nisi luctus et. Ut ullamcorper, nulla eget porta dictum, libero ligula mollis diam, ac lacinia eros eros porta erat. In ac ultrices erat, non rhoncus est. Quisque sem lacus, pellentesque et dui sed, tempus malesuada eros. Ut tempor velit et libero convallis auctor. In justo nisi, efficitur vitae metus vel, convallis convallis sapien. Aenean semper ultrices mattis. Praesent aliquet nisi a tellus lobortis porttitor. Aenean neque turpis, iaculis fringilla aliquam id, pharetra sit amet dolor. Proin dignissim suscipit eros, ut cursus justo suscipit ac. Duis quam sem, suscipit eu vestibulum ut, tincidunt non dui. Nullam suscipit sit amet magna ac semper.</p>
            <p>Fusce scelerisque tincidunt nulla, sit amet placerat neque volutpat quis. Proin magna purus, ultrices sit amet imperdiet ac, maximus vel augue. Fusce sit amet ornare turpis. Ut cursus massa eget tellus condimentum posuere a a urna. Vestibulum rutrum auctor felis non elementum. Integer mi nulla, egestas et semper non, porttitor at diam. In rhoncus, metus ut aliquet lobortis, est est scelerisque sem, et pulvinar lacus mauris ac mi. Phasellus ut sapien sapien. Suspendisse potenti. Vestibulum rhoncus eget metus in condimentum. Nunc vitae massa ac eros imperdiet vestibulum.</p>
            <p>Etiam in nulla vitae tellus placerat sollicitudin et in metus. Nulla aliquet nibh non ultricies gravida. Vivamus at massa lacus. Vestibulum porttitor quam et faucibus bibendum. Mauris vel ultrices lacus, id bibendum purus. Curabitur facilisis est et lacinia convallis. Mauris tristique consectetur dui, sed porta velit mattis a.</p>
            <p>Phasellus dapibus dolor eu pulvinar ultricies. Duis fermentum justo urna, pharetra varius felis ullamcorper at. Sed dictum aliquet posuere. Aliquam nec dignissim tellus. Cras rhoncus purus vitae sapien ornare sodales. Nam finibus arcu vel neque tincidunt, sed accumsan augue condimentum. Proin dapibus sodales diam congue auctor. Nunc et velit ac arcu imperdiet dapibus. Etiam dapibus odio ante, id sagittis ante lacinia quis. Curabitur quis varius ex, nec gravida ex. Sed sem est, lacinia malesuada nisi vitae, blandit vulputate ipsum. Praesent egestas scelerisque tortor, eu porttitor orci accumsan in. Vivamus lacinia tortor id leo consectetur bibendum. Etiam egestas sem nec lacus fermentum, eu scelerisque metus commodo.</p>
            <p>Nunc pretium cursus diam, non auctor lorem convallis sit amet. Quisque interdum turpis in lacus imperdiet ultrices. Donec venenatis metus in laoreet mattis. Pellentesque mollis lorem leo, vel dictum nisl tincidunt quis. Morbi erat ipsum, lobortis ut porta ut, commodo quis nibh. Nulla suscipit nunc at sem aliquet, quis placerat elit tincidunt. Sed interdum sollicitudin turpis, a molestie felis placerat posuere. Donec ac quam faucibus, posuere risus vitae, pretium lorem. Morbi hendrerit libero at ligula volutpat eleifend.</p>
            <p>Praesent eu risus vel orci pellentesque venenatis id in eros. Aliquam a odio est. Proin hendrerit volutpat porttitor. Etiam vehicula elit nec dui fermentum, eget ultrices eros venenatis. Fusce euismod eros nec pharetra aliquet. Curabitur porttitor ligula et tempus fringilla. Curabitur imperdiet sagittis mauris ac laoreet. Mauris eget ullamcorper nulla. Nullam sodales dictum risus, id finibus lorem gravida a. In hac habitasse platea dictumst. Pellentesque a mi ac lectus congue fringilla. Curabitur vel risus commodo, commodo lorem vel, sollicitudin ante.</p>
            <p>Vivamus ac rhoncus tortor, sed ultricies metus. Pellentesque condimentum at tortor in volutpat. Vestibulum tristique tristique erat nec volutpat. Ut non est eu tellus malesuada ornare. Etiam vulputate magna leo, pharetra malesuada sem scelerisque vel. Morbi sagittis, urna et cursus suscipit, lorem augue luctus ante, eget lacinia tellus lorem at augue. Nulla hendrerit nunc a sem elementum sagittis. Praesent tincidunt cursus velit. Morbi convallis vel libero et posuere. Mauris mi leo, consequat sed odio in, volutpat tempus diam.</p>
            <p>Vivamus maximus pharetra tempus. Fusce rutrum, nunc vitae dictum tincidunt, dolor ligula volutpat leo, id porta justo ipsum sed risus. Nunc iaculis erat non pharetra accumsan. Quisque ut finibus metus. Nunc ullamcorper bibendum odio eget aliquet. Duis vehicula sed turpis semper cursus. Praesent quis tristique ligula, elementum eleifend metus. Pellentesque vulputate lacus sit amet dui suscipit maximus. Suspendisse gravida eleifend turpis, quis aliquam diam.</p>
            <p>Etiam pretium sodales odio, vitae aliquam libero luctus ut. Morbi magna nibh, aliquam eget pretium placerat, maximus quis elit. Donec ultrices turpis eu lacus sagittis malesuada. Integer lectus libero, consequat vitae convallis vitae, lacinia ac odio. Maecenas tempus pulvinar est, a interdum arcu cursus ac. Donec turpis augue, varius vitae congue a, fringilla sed neque. Fusce molestie sapien justo, vel convallis turpis molestie vel. Aenean sed augue accumsan tortor consequat auctor nec vitae odio. In ac lectus pretium turpis fermentum vulputate. Sed gravida dictum elit a maximus.</p>
            <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam bibendum mauris non neque iaculis, sed cursus est venenatis. Ut ut pretium urna. Nulla facilisi. Nulla at leo porta, aliquam turpis vel, mattis est. Suspendisse finibus diam vel mattis commodo. In viverra, enim sit amet volutpat dapibus, purus turpis fermentum ante, ac ullamcorper mauris enim ut leo. Morbi vitae neque at nulla luctus hendrerit at tincidunt risus. Nullam ut ultricies sapien. Integer sollicitudin leo ornare lectus porta aliquam. Nam rhoncus non mi id posuere. In consequat, sem in convallis mollis, lacus velit feugiat lectus, a rutrum nisl dui elementum nunc. Sed vel neque dui. Pellentesque ultrices sollicitudin tortor, sit amet condimentum justo gravida mollis. Duis euismod porta orci sed vestibulum. Maecenas sed erat vehicula, blandit felis ut, gravida magna.</p>
            <p>Pellentesque dignissim, felis sed molestie blandit, nibh justo volutpat orci, volutpat tempor ex eros id ligula. In et vulputate dui, porttitor ullamcorper nunc. Phasellus tortor magna, volutpat et purus in, dignissim condimentum lectus. Donec eleifend, erat id placerat iaculis, massa nulla ultricies enim, dignissim sodales metus enim a ipsum. Quisque vel turpis sit amet lorem fermentum dapibus. Praesent vulputate malesuada sapien vel finibus. Integer sollicitudin ipsum urna, et venenatis leo tristique vel. Etiam eget diam non ligula pretium pharetra condimentum ac velit. Phasellus tortor lacus, feugiat non iaculis non, vulputate non velit. In hac habitasse platea dictumst. Donec velit nibh, pulvinar eget elit et, tempus fermentum lectus. Donec quis rutrum est. Sed imperdiet, odio nec consequat tempor, erat augue aliquam odio, eu dictum leo orci et orci. Vestibulum at lectus vel nisi rutrum luctus. Maecenas sed nulla elementum, egestas orci vel, faucibus nisi.</p>
            <p>Praesent vel sem tortor. Vivamus elementum venenatis velit, sit amet feugiat lacus congue ut. Ut aliquet gravida lorem et lacinia. Proin eu nisi sit amet mi fringilla condimentum fringilla at mi. Pellentesque eget arcu nunc. Nulla pulvinar ligula non pellentesque semper. Fusce tempor ornare eleifend. Duis porta sapien in enim rhoncus, ut vulputate elit congue. Ut efficitur accumsan aliquet. Donec at lectus quis urna finibus fringilla. Phasellus lobortis sollicitudin lectus, eu condimentum nulla porttitor quis. Vestibulum vulputate ut felis vel semper. Cras vehicula sapien sapien, pretium pretium dolor suscipit in. Aliquam posuere tincidunt turpis, quis ultricies massa viverra eget. In ut mi consequat, vehicula arcu vitae, venenatis magna. Nunc molestie ligula vel nibh egestas finibus.</p>
            <p>Donec pulvinar sapien vitae leo congue luctus. Nunc a gravida velit. Curabitur dignissim ultrices enim, nec ornare turpis tincidunt sed. Etiam in magna fermentum justo elementum hendrerit ut in turpis. Donec quis auctor diam, ac auctor nisl. Nunc commodo ultrices leo non mattis. Phasellus tellus odio, convallis ac mauris et, tempus tempor enim. Vivamus varius tortor non urna tempor, non porta tortor lacinia. Donec lobortis diam vitae ante varius tincidunt. Suspendisse quis urna sit amet urna vehicula pretium. Vivamus dui leo, tristique vitae neque vel, volutpat semper purus. Donec non nunc purus. Mauris volutpat nulla non ultricies efficitur.</p>
          </div>
        ))}
      </div>
    )
  }
}
